fix: block beneficiary update
gip-inclusion/carnet-de-bord pull request #1274
Opened 2022-11-21 21:36 UTC by lionelB

## :wrench: Problème

Actuellement, la mise à jour via import peut entrainer une perte d'information du bénéficiaire ou dans son carnet.

## :cake: Solution

On bloque temporairement la mise à jour via import 

## :rotating_light:  Points d'attention / Remarques

> _Précisez si il y a des cas particuliers ou des sujets connexes à partager ?_

## :desert_island: Comment tester

> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

Ne pas supprimer ce bloc, qui sera mis à jour [automatiquement](.github/workflows/review-scalingo.yml).

fix #1273

2022-11-22 08:31 UTC, lionelB commented
Oui pour l'instant on bloque car le fix du réimport etait pas encore dans le sprint et que c'est pas un trucs rapide

2022-11-23 12:54 UTC, HEYGUL commented on app/src/lib/ui/Manager/ImportBeneficiaries.svelte
> +		console.log(value);
supprimer ce `console.log`

2022-11-23 12:54 UTC, HEYGUL commented on app/src/lib/ui/Manager/ImportBeneficiaries.svelte
> +		console.log(value);
On devrait peut-être mettre cette fonction dans `format`.
A voir si on peut améliorer le typage de `value`.

2022-11-23 12:54 UTC, HEYGUL commented on backend/api/db/models/validator.py
> +        print(value, value.lower() in ["oui", "o"])
supprimer ce `print`

2022-11-23 14:57 UTC, jonathanperret requested changes
Quelques notes vues aussi en direct ensemble

2022-11-23 20:36 UTC, lionelB commented
@jonathanperret j'ai fini le refacto lié à la review. je le laisse valider si c'est bon de ton coté

2022-11-23 20:57 UTC, HEYGUL commented on backend/api/db/crud/account.py
> +    Since email are store in different tables (manager / professional / orientation_manager)
```suggestion
    Since email addresses are stored in different tables (manager / professional / orientation_manager)
```

2022-11-24 19:35 UTC, jonathanperret approved these changes

2022-11-24 19:35 UTC, jonathanperret commented on app/src/lib/ui/format.ts
> +export function displayBoolean(value: unknown): string | null {
Quand cette fonction reçoit une valeur qui ne respecte pas `typeof value === 'boolean'`, elle retourne `undefined` et non `null`…

2022-11-24 19:35 UTC, jonathanperret commented on backend/api/db/models/beneficiary.py
> +    # TODO Shoulb be possible to use decorator to mark field for beneficiary
```suggestion
    # TODO Should be possible to use decorator to mark field for beneficiary
```

2022-11-24 19:50 UTC, lionelB commented on app/src/lib/ui/BeneficiaryList/FilterOrientation.svelte
> +		console.error(withoutOrientationManager);
je m'en occupe

2022-11-28 14:05 UTC, merged

2022-11-28 14:06 UTC, service-dev-gip-inclusion commented
:tada: This PR is included in version 1.162.1 :tada:

The release is available on [GitHub release](https://github.com/gip-inclusion/carnet-de-bord/releases/tag/v1.162.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: