Feat/conservation historique du groupe de suivi
gip-inclusion/carnet-de-bord pull request #1338
Opened 2022-12-08 08:00 UTC by bChiquet

## :wrench: Problème

> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :cake: Solution

> _Décrivez en quelques mots la solution retenue et mise en oeuvre, les difficultés ou problèmes rencontrés._

## :rotating_light:  Points d'attention / Remarques

> _Précisez si il y a des cas particuliers ou des sujets connexes à partager ?_

## :desert_island: Comment tester

> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

Ne pas supprimer ce bloc, qui sera mis à jour [automatiquement](.github/workflows/review-scalingo.yml).

2022-12-13 22:22 UTC, lionelB commented on backend/api/v1/routers/_acceptOrientationRequest.gql
>        memberType: { _eq: "referent" }
```suggestion
      memberType: { _eq: "referent" }
      active: { _eq: true }
```

2022-12-20 11:56 UTC, lionelB commented on backend/api/v1/routers/change_beneficiary_orientation.py
> +    def gql_variables_for_mutation(
cette fonction n'est plus utilisée, on peut la supprimer

2022-12-20 11:57 UTC, lionelB commented on backend/api/v1/routers/change_beneficiary_orientation.py
>          notification_response = await session.execute(
Est ce qu'on renomme cette variable ? ping @jonathanperret

2022-12-20 11:59 UTC, lionelB commented on backend/api/v1/routers/change_beneficiary_orientation.py
> +                mutations = mutations | {
on peut deplacer ce bloque de code en dehors du try

2022-12-20 12:29 UTC, jonathanperret commented on backend/api/v1/routers/change_beneficiary_orientation.py
>          notification_response = await session.execute(
Dans la mesure où cette valeur est utilisée pour bien plus que de la notification maintenant, je pense que ce serait effectivement pertinent…

2022-12-20 13:15 UTC, HEYGUL commented on backend/api/v1/routers/notificationInfo.gql
>  query notificationInfos(
il faudra renommer le fchier et la query également

2022-12-20 14:18 UTC, HEYGUL commented on backend/api/v1/main.py
> +        print(query)
on peut supprimer les différents `print`

2022-12-20 14:18 UTC, HEYGUL commented on backend/api/v1/main.py
> +async def getSchema():
dans quel contexte se sert-on de cette route ?

2022-12-20 14:22 UTC, HEYGUL commented on backend/api/v1/routers/change_beneficiary_orientation.py
> +    """
est-ce qu'on peut mettre cette description de telle sorte qu'elle apparaisse dans la documentation openAPI ?

2022-12-20 14:23 UTC, HEYGUL commented on backend/api/v1/routers/change_beneficiary_orientation.py
> +        if orientation_info_response["notebook_by_pk"]["former_referents"]:
la fonction qui suit est longue à lire, je propose de refactorer par exemple en sortant les contenus de certains if dans des fonctions dédiées

2022-12-20 14:40 UTC, lionelB commented on backend/api/v1/main.py
> +        print(query)
j'ai supprimé le endpoint c'etait du test

2022-12-20 14:40 UTC, lionelB commented on backend/api/v1/main.py
> +async def getSchema():
c'est supprimé, c'etait pour tester

2022-12-20 14:41 UTC, lionelB commented on backend/api/v1/routers/orientation_info.gql
>  query notificationInfos(
bien vu!

2022-12-21 11:20 UTC, lionelB requested changes
on doit faire une modif pour rajouter le schema graphql avec une etape de build

2022-12-21 20:44 UTC, HEYGUL commented on backend/tests/api/test_change_beneficiary_orientation.py
>      guilia_diaby_jwt: str,
pas lié à cette PR, mais on pourrai corriger la typo sur `giuilia` au passage

2022-12-22 16:23 UTC, lionelB approved these changes

2022-12-22 18:35 UTC, HEYGUL approved these changes

2022-12-22 21:12 UTC, merged

2022-12-22 21:13 UTC, service-dev-gip-inclusion commented
:tada: This PR is included in version 1.178.0 :tada:

The release is available on [GitHub release](https://github.com/gip-inclusion/carnet-de-bord/releases/tag/v1.178.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: