fix(manager): mise à jour de la liste bénéficiaires et du dashboard
gip-inclusion/carnet-de-bord pull request #1537
Opened 2023-02-20 09:51 UTC by lionelB

## :wrench: Problème

 la home affiche un nombre de bénéficiaires qu'on ne retrouve pas lorsqu'on affiche la liste des bénéficiaires. Le dénombrement de l'accueil etait faux (nombre de bénéficiaire sans structure ou sans membre actif dans le groupe de suivi et le filtre de la liste bénéficiaire qui filtrer les bénéficiaires avec ou sans référent.

## :cake: Solution
On met à jour les filtres avec  accompagnés, non accompagnés, et en attente de référent à la liste des bénéficiaires

## :rotating_light:  Points d'attention / Remarques

On en profite pour mettre à jour le dashboard manager (et ses test e2e)

## :desert_island: Comment tester

Se connecter en tant que `manager.cd93`
Suivre les liens   `bénéficiaires non accompagnés` depuis l'accueil du dashboard
Constater qu'on a bien 2 bénéficiaires

Ne pas supprimer ce bloc, qui sera mis à jour [automatiquement](.github/workflows/review-scalingo.yml).

fix #1489

2023-02-20 10:40 UTC, JonathanRaimond commented
Le décompte se fait correctement pour les bénéficiaires sans structures et sans référent. Comme dit @charles.dechamps il faut aussi voir dans la liste filtrée, les bénéficiaires en attente de référent. Si un bénéficiaire est rattaché à une structure et non à un référent, alors on ne pas considérer qu'il est accompagné. ETQ manager je peux voir que je n'ai que 2 bénéficiaires sans accompagnements alors qu'en réalité, il y en a 40 qui ne sont pas encore accompagnés par un référent.

Etant donné que, suis manager et que je suis le dashboard de mon déploiement,
Lorsque, je clique sur le btn "Bénéficiaires non accompagnés",
Alors, je vois la liste des bénéficiaires filtrée contenant :
- Bénéficiaires sans structure et sans référent
- Bénéficiaires avec structure et sans référent

2023-02-23 08:05 UTC, chdechamps requested changes
Pas ok. 

Lorsqu'en tant que pro, je me rattache a un carnet sans mandat, et donc sans devenir le référent du bénéficiaire et sans qu'il n'ait été orienté vers ma structure, le bénéficiaire est considéré dans CdB comme ayant été orienté vers la structure (ce qui ne devrait pas être le cas). 

Pour reproduire : 
- Via Pierre Chevallier, je me suis rattaché à Buckley Hoffman en tant que pro sans mandat (donc non référent). 
- Buckley Hoffman apparait dans les bénéficiaires a orienter de Jacques Celaire (gestionnaire de la structure de Pierre, ça ne devrai pas)
- Buckley Hoffman apparait comme orienter vers le CCAS en attente d'un référent pour manager.cd93 (ce qui ne devrait pas)
- Buckley Hoffman apparait comme un bénéficiaire orienté en attente d'un référent pour Giulia (ce qui risque d'engendrer des bénéficiaires en rupture de parcours puisqu'il ne sera donc pas visible pour Giulia (sauf s'il prends lui meme rdv)). 

Par contre, Ok avec la mise en place du filtre dans "tous les bénéficiaires" pour les bénéficiaires en attente d'un référent.

2023-02-23 10:42 UTC, lionelB commented
@chdechamps pour le coup tu viens de tomber sur un bug qui n'a rien à voir avec la PR, je viens de créer l'issue #1551

2023-02-24 12:03 UTC, chdechamps approved these changes

2023-02-24 12:53 UTC, HEYGUL commented on app/src/lib/ui/BeneficiaryList/SupportFilters.svelte
> +<form on:submit|preventDefault={onSubmit}>
Pourquoi ne pas utiliser le composant `Form.svelte` ?
(et par conséquent les `Select.svelte` qui sont dans le répertoire `Form`)

2023-02-24 12:53 UTC, HEYGUL commented on app/src/routes/(auth)/manager/+page.svelte
> +			classNames: beneficiaryWithoutStructureCount ? 'text-marianne-red' : 'text-success',
```suggestion
			classNames: beneficiaryWithoutStructureCount > 0 ? 'text-marianne-red' : 'text-success',
```

2023-02-24 12:53 UTC, HEYGUL commented on app/src/routes/(auth)/manager/+page.svelte
> +			classNames: structuresWithNoBeneficiaryCount ? 'text-marianne-red' : 'text-success',
```suggestion
			classNames: structuresWithNoBeneficiaryCount > 0 ? 'text-marianne-red' : 'text-success',
```

2023-02-27 08:45 UTC, lionelB commented on app/src/lib/ui/BeneficiaryList/SupportFilters.svelte
> +<form on:submit|preventDefault={onSubmit}>
parcce que c'était plus rapide à faire (les autres composant filters sont sur ce principe) et que je ne cherche pas à valider les entrées

2023-02-27 09:22 UTC, lionelB commented on app/src/lib/ui/BeneficiaryList/SupportFilters.svelte
> +<form on:submit|preventDefault={onSubmit}>
J'ai mis à jour avec le Form

2023-02-27 19:42 UTC, HEYGUL approved these changes

2023-02-27 19:42 UTC, merged

2023-02-27 19:43 UTC, service-dev-gip-inclusion commented
:tada: This PR is included in version 1.201.4 :tada:

The release is available on [GitHub release](https://github.com/gip-inclusion/carnet-de-bord/releases/tag/v1.201.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: