fix: add deploymentId to  internalId unicity constraint
gip-inclusion/carnet-de-bord pull request #1589
Opened 2023-03-14 09:26 UTC by lionelB

## :wrench: Problème

Actuellement le champ internalId qui était censé faciliter le réimport de bénéficiaire en attendant le NIR avait une contrainte d'unicité sur l'ensemble de la base or il arrive régulièrement qu'il y ait des collisions pendant les imports de nouveaux territoires.

## :cake: Solution

On modifie la contraintes pour prendre en compte le deploiement et éviter ainsi les collisions d'internalId hors d'un déploiement.

## :rotating_light:  Points d'attention / Remarques

Lorsque l'emploi du nir sera effectif, il faudra s'interroger sur le maintien de cette contrainte et du champ `internalId` ?

## :desert_island: Comment tester

La contrainte a été testé sur la base de prod au sein d'un transaction.

fix #1585

2023-03-14 09:30 UTC, francoisfreitag commented
Sympa le test de support de l’unicode dans les noms de branches :stuck_out_tongue: 

Je ne suis pas assez familier avec le métier, mais  ça fait bien ce que ça dit. :+1:

2023-03-14 12:38 UTC, HEYGUL requested changes
Il faudrait a minima ajouter une vérification du `deployment_id` [ici](https://github.com/gip-inclusion/carnet-de-bord/blob/7325944f18f5073d2ab82ddef1585fed63568384/backend/cdb/api/v1/routers/beneficiaries.py#L198-L199) et [là](https://github.com/gip-inclusion/carnet-de-bord/blob/7325944f18f5073d2ab82ddef1585fed63568384/backend/cdb/api/v1/routers/beneficiaries.py#L204-L205)

Idéalement on ajoute un test pour montrer qu'on peut avoir 2 `internalId` identiques dans 2 déploiements différents, mais dans le même déploiement.

2023-03-14 19:15 UTC, HEYGUL approved these changes

2023-03-15 17:33 UTC, merged

2023-03-15 17:34 UTC, service-dev-gip-inclusion commented
:tada: This PR is included in version 1.206.1 :tada:

The release is available on [GitHub release](https://github.com/gip-inclusion/carnet-de-bord/releases/tag/v1.206.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: