Ajout d'impact métier et KPI au modèle d'issues
gip-inclusion/carnet-de-bord pull request #1650
Opened 2023-04-04 14:09 UTC by chdechamps

## :wrench: Problème

Le modèle d'issues n'a pas d'emplacement pour l'impact métier / KPI qui manque parfois pour comprendre l'intéret d'une issues

## :cake: Solution

Ajout d'emplacements Impact métier et KPI au fichier modèle. 

## :rotating_light:  Points d'attention / Remarques

> _Précisez si il y a des cas particuliers ou des sujets connexes à partager ?_

## :desert_island: Comment tester

> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-04-05 07:44 UTC, vjousse requested changes

2023-04-05 07:44 UTC, vjousse commented on .github/ISSUE_TEMPLATE/fonctionnalite.md
> +> ex: En tant que chargé d'orientation, j'ai besoin de connaître dans carnet de bord le capacité d'accueil d'un pro pour choisir le professionnel vers qui orienté un bénéficiaire.
```suggestion
> ex: En tant que chargé d'orientation, j'ai besoin de connaître, dans carnet de bord, la capacité d'accueil d'un pro pour choisir le professionnel vers qui orienter un bénéficiaire.
```

2023-04-05 07:44 UTC, vjousse commented on .github/ISSUE_TEMPLATE/fonctionnalite.md
> +ex: Cette US a pour but de permettre aux CO d'orienter les bénéficiaires vers un accompagnerment en capacité à prendre en charge l'usager (lutter contre les ruptures de parcours)
```suggestion
ex: Cette US a pour but de permettre aux CO d'orienter les bénéficiaires vers un accompagnement en capacité de prendre en charge l'usager (lutter contre les ruptures de parcours)
```

2023-04-05 07:44 UTC, vjousse commented on .github/ISSUE_TEMPLATE/fonctionnalite.md
> +ex: Nombre de jour entre la réalisation du diag et la définition de l'orientation.
```suggestion
ex: Réduction du nombre de jours entre la réalisation du diag et la définition de l'orientation.
```

2023-04-06 08:40 UTC, lionelB approved these changes

2023-04-13 08:32 UTC, vjousse approved these changes

2023-04-13 08:44 UTC, merged

2023-04-13 08:44 UTC, service-dev-gip-inclusion commented
:tada: This PR is included in version 1.213.10 :tada:

The release is available on [GitHub release](https://github.com/gip-inclusion/carnet-de-bord/releases/tag/v1.213.10)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: