♻ Réécriture des actions en Elm
gip-inclusion/carnet-de-bord pull request #1718
Opened 2023-05-03 12:27 UTC by HadrienMP

## :wrench: Problème

L'équipe a décidé de faire la transition vers Elm. La story #1645 implique de modifier un composant svelte.

## :cake: Solution

Il a été décidé de réécrire le composant en Elm pour faire l'ajout.

## :rotating_light:  Points d'attention / Remarques

Dans cette PR, il y a : 
- la réécriture
- la documentation avec storybook
- des tests de la page avec elm-test

Les mises à jour avec graphql sont déléguées à svelte pour que les impacts ailleurs dans le site soient bien réalisés. Cela implique une adhérence plus importante que ce que j'imaginais avec l'application svelte.

## :desert_island: Comment tester

En tant que professionnel
- aller sur un carnet de bord
- cliquer sur un plan d'action
- déplier un objectif

1. Modifier le statut d'une action 
    - le passage à un autre statut que "en cours" décompte l'action du compte affiché sur le plan d'action sous la modale
2. Ajouter une action
    - elle est ajoutée à la liste et 
    - prise dans le compte pour le plan d'action

2023-05-03 15:11 UTC, HadrienMP commented on app/.storybook/elm-storybook/Storybook/Component.elm
Je permet l'appel de fonctions init qui ont des effets de bord. À voir si c'est judicieux ou non.

2023-05-03 15:11 UTC, HadrienMP commented on app/.storybook/elm-storybook/Storybook/Controls.elm
> +            , fallback = options.fallback
J'ai viré ce Decode.oneOf, il rend trop difficle le debugging parce que si on s'est planté sur le décodeur, il prend la valeur par défaut. Un plantage visuel sur storybook est plus compréhensible.

2023-05-03 15:11 UTC, HadrienMP commented on app/elm/DiagnosticEdit/RomeSelect.elm
> +getRome : Api -> { search : String, callbackMsg : Result Http.Error (List Rome) -> Msg } -> Cmd Msg
J'ai rajouté Http.Error pour pouvoir logger sur Sentry a minima

2023-05-03 15:11 UTC, HadrienMP commented on app/elm/Pages/Pro/Carnet/Action/List/Main.elm
Le module Main me sert d'adapter. Il a pour rôle de récupérer les actions et les passer à la page. Ça permet de plus facilement faire le design avec storybook et faire des tests automatisés

2023-05-03 15:11 UTC, HadrienMP commented on app/elm/README.md
> +	import { Elm } from '$elm/MainApp/Main.elm';
J'ai ajouté un alias d'import svelte/ts pour ne plus avoir à faire ces imports elm compliqués

2023-05-03 15:11 UTC, HadrienMP commented on app/elm/UI/SearchSelect/Component.elm
> +    | Select a
J'ai du rajouter ce message pour permettre de tester automatiquement ce composant. Le select de confidenceman n'ouvre pas de message pour la sélection.

2023-05-03 15:11 UTC, HadrienMP commented on app/src/lib/utils/ElmWrapper.svelte
J'ai fait ce petit wrapper svelte pour simplifier l'inclusion de elm dans une page en respectant les tricks

2023-05-03 15:11 UTC, HadrienMP commented on docker-compose-test.yaml
> +      - '${HASURA_ENDPOINT_PORT:-5001}:8080'
J'avais besoin de l'utilisation de cette variable car sur mon "Bonjour" occupe le port 5000. Ça décale tous mes ports Hasura de 1.

2023-05-03 15:11 UTC, HadrienMP commented on hasura/metadata/databases/carnet_de_bord/tables/public_notebook_action.yaml
Modifications de permissions qu'on a fait ensemble avec @lionelB

2023-05-03 15:11 UTC, HadrienMP commented on hasura/migrations/carnet_de_bord/1683096909827_search_ref_action/up.sql
Pour que le composant de recherche soit le même que code Rome, il fallait une query de recherche

2023-05-09 18:38 UTC, HEYGUL approved these changes

2023-05-10 08:16 UTC, vjousse requested changes
Je préférerais qu'on laisse les noms de variables et de fonctions en anglais plutôt que de prendre le risque de mixer français / anglais et de finir par s'y perdre.

2023-05-10 08:49 UTC, HadrienMP commented on app/elm/Pages/Pro/Carnet/Action/List/ActionSelect.elm
> +            """ |> String.trim
C'est un réflexe que j'ai avec les multiline string, mais effectivement ça ne doit pas gêner

2023-05-10 13:59 UTC, vjousse approved these changes
Joli taf ! C'est ok pour moi, il faudrait juste supprimer le `createurDecoder` qui est encore en français

2023-05-10 13:59 UTC, vjousse commented on app/elm/Pages/Pro/Carnet/Action/List/AllActions.elm
> +        |> Decode.required "lastname" Decode.string
Merger ça dans la même fonction pour éviter d'avoir ce `createurDecoder` en français ?

2023-05-10 14:27 UTC, merged