feat: Ajout d'un dry-run pour la synchronisation Pôle emploi
gip-inclusion/carnet-de-bord pull request #1958
Opened 2023-08-10 09:35 UTC by vjousse

## :wrench: Problème

Actuellement, la synchronisation avec l'API PE n'est pas activée par manque d'informations sur les effets que cela produirait dans Cdb.

## :cake: Solution

On ajoute un mode `dry-run` à la synchronisation qui va permettre d'avoir des logs des actions qui seraient réalisées dans Cdb (ajout / modification / suppression) à la suite de la synchronisation des contraintes.

## :desert_island: Comment tester

TODO

fix #1952

2023-08-17 07:15 UTC, lionelB commented on backend/cdb/api/v1/routers/pe_diagnostic/pe_diagnostic.py
> +    else:
je propose qu'on active ces log seulement pour le dry-run pour éviter d'avoir des log inutiles quand tout fonctionne correctement

2023-08-17 07:15 UTC, lionelB commented on backend/cdb/api/v1/routers/pe_diagnostic/pe_diagnostic.py
> +        logger.info(
```suggestion
        logger.debug(
```

2023-08-17 07:16 UTC, lionelB commented on backend/cdb/api/v1/routers/pe_diagnostic/pe_diagnostic.py
> +        logger.info(
```suggestion
        logger.debug(
```

2023-08-17 07:33 UTC, lionelB commented on backend/cdb/api/db/crud/notebook.py
> +    notebook_ids: list[UUID] = []
pourquoi ne pas avoir utiliser gql ici ?

2023-08-19 09:16 UTC, vjousse commented on backend/cdb/api/db/crud/notebook.py
> +    notebook_ids: list[UUID] = []
Pourquoi le faire en fait ? Personnellement pour récupérer une liste d'id je trouvais ça plus pratique, mais peu me chaut ^^

2023-08-28 07:41 UTC, HadrienMP requested changes

2023-08-28 07:41 UTC, HadrienMP commented on backend/cdb/api/db/crud/notebook.py
> +        print(
C'est normal le print ?

2023-08-28 07:41 UTC, HadrienMP commented on backend/cdb/api/v1/routers/pe_diagnostic/pe_diagnostic.py
> +            "[notebook_id: %s] No fresh data for notebook (<1 hour), skipping",
Pour la récupération des logs, est-ce qu'un préfixe ne pourrait pas être utile ? [PE] par exemple ?

2023-08-28 08:32 UTC, lionelB commented on backend/cdb/api/db/crud/notebook.py
> +    notebook_ids: list[UUID] = []
> "Pourquoi le faire"

Il me semble que c'était ce qu'on avait décidé dans l'adr (recentrer l'archi sur Hasura) mais je  te rejoins sur la practicité pour des select simple, je trouve plus facile à lire que gql.

2023-08-28 08:59 UTC, vjousse commented on backend/cdb/api/v1/routers/pe_diagnostic/pe_diagnostic.py
> +            "[notebook_id: %s] No fresh data for notebook (<1 hour), skipping",
Yes pourquoi pas, même si le log reste préfixé par le nom du fichier `[2023-08-16 16:22:05,653:pe_diagnostic.py:153 - update_notebook_from_pole_emploi() ]`, ça peut peut-être aider :blush:

2023-08-28 09:00 UTC, vjousse commented on backend/cdb/api/db/crud/notebook.py
> +        print(
Non :sweat_smile:

2023-08-28 09:31 UTC, HadrienMP commented on backend/cdb/api/v1/routers/pe_diagnostic/pe_diagnostic.py
> +            "[notebook_id: %s] No fresh data for notebook (<1 hour), skipping",
Ah ouais, pas besoin du coup

2023-08-28 09:32 UTC, HadrienMP approved these changes

2023-08-28 10:26 UTC, merged

2023-08-28 10:27 UTC, service-dev-gip-inclusion commented
:tada: This PR is included in version 1.254.0 :tada:

The release is available on [GitHub release](https://github.com/gip-inclusion/carnet-de-bord/releases/tag/v1.254.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: