feat: historise les changements d'orientation
gip-inclusion/carnet-de-bord pull request #1990
Opened 2023-08-30 13:31 UTC by lionelB

## :wrench: Problème

Il est impossible actuellement de pouvoir visualiser l'évolution des types d'accompagnement d'un bénéficiaire. Cela rend compliqué de faire le lien avec le travail d'accompagnement précédemment réalisé et d'éviter de renvoyer les bénéficiaires sur un dispositif déjà mobilisé.

## :cake: Solution
On ajoute dans l'historique une ligne à chaque orientation / réorientation.
En terme de statut, sera en cours jusqu'à une nouvelle (ré)orientation et dans ce cas, le statut doit passer à clos.

## :rotating_light:  Points d'attention / Remarques

On aggrège dans le champs event les infos courantes (dispositif, structure, référent si défini) et leur valeurs précédentes

## :desert_island: Comment tester

Se connecter en tant que giulia diaby
aller sur le carnet de sophie tifour
Réorienter dans différent dispositif et voir les évènements correspondant.

fix #1984

2023-08-30 15:25 UTC, chdechamps approved these changes

2023-09-04 11:37 UTC, JonathanRaimond approved these changes

2023-09-04 13:43 UTC, lionelB commented on app/src/lib/ui/NotebookEvent/NotebookEventList.svelte
> +		console.log(
```suggestion
		console.log(
```

2023-09-04 13:44 UTC, lionelB commented on app/src/lib/ui/NotebookEvent/NotebookEventList.svelte
> +		);
```suggestion
```

2023-09-05 07:30 UTC, vjousse requested changes

2023-09-05 07:30 UTC, vjousse commented on app/src/lib/constants.ts
> +		name: NotebookEventTypeEnum.Orientation,
Pourquoi le label est 'Réorientation' et la valeur de l'enum 'Orientation' ?

2023-09-05 07:30 UTC, vjousse commented on app/src/lib/ui/NotebookEvent/NotebookEventList.svelte
> +		if (notebookEvent.eventType === NotebookEventTypeEnum.Orientation) return '(Ré)orientation';
Pourquoi ne pas changer le label plus haut et le retourner ici comme on pourrait s'y attendre ?

2023-09-05 07:30 UTC, vjousse commented on app/src/lib/ui/NotebookEvent/NotebookEventList.svelte
> +		const status_string = statusValues.find((v) => v.name == status);
Pourquoi enlever la type annotation ici ? Perso j'aime bien quand c'est explicite !

2023-09-05 07:30 UTC, vjousse commented on backend/cdb/api/db/crud/orientation_info.py
> +    print(orientation_info_response)
```suggestion
```

2023-09-05 14:12 UTC, lionelB commented on app/src/lib/ui/NotebookEvent/NotebookEventList.svelte
> +		const status_string = statusValues.find((v) => v.name == status);
Je ne trouve au contraire qu'elle apporte du bruit (sachant que le type est déjà défini plus haut)
je les enlevées car le compilateur pouvait justement les déduire.

2023-09-06 07:59 UTC, vjousse commented on app/src/lib/ui/NotebookEvent/NotebookEventList.svelte
> +		const status_string = statusValues.find((v) => v.name == status);
On n'est pas d'accord là dessus (j'adore les type annotations explicites), mais les goût et les couleurs… :smile:

2023-09-06 08:20 UTC, vjousse approved these changes

2023-09-06 08:20 UTC, merged

2023-09-06 08:21 UTC, service-dev-gip-inclusion commented
:tada: This PR is included in version 1.259.0 :tada:

The release is available on [GitHub release](https://github.com/gip-inclusion/carnet-de-bord/releases/tag/v1.259.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: